//! Build script: embed the repo-root `metadata/` data files that `ls-core`
//! consumes at runtime.
//!
//! `metadata/` lives at the workspace root, outside this crate, so a bare
//! `include_str!` would need a non-publish-safe `../../../` escape (KTD2 of the
//! error-resilience gate plan). Instead we read the files here and emit a small
//! generated module (`embedded_metadata.rs` in `OUT_DIR`) holding their contents
//! as `&'static str` literals, which `src/error_catalog.rs` / `src/preflight.rs`
//! `include!`. Consumers get the data with zero filesystem access.
//!
//! Two artifacts are embedded:
//! - `metadata/error-catalog.yaml` → `ERROR_CATALOG_YAML` (the shared gateway-code
//!   explanation catalog; U1).
//! - every `metadata/constraints/*.yaml` → `CONSTRAINT_FILES` (per-TR request
//!   field-constraint schemas driving preflight validation; U2/U3). The set is
//!   dynamic — a TR earns a preflight schema by having a file here — so the list
//!   is globbed, not hand-listed.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let metadata_dir = Path::new(&manifest_dir).join("..").join("..").join("metadata");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("embedded_metadata.rs");

    // Re-run if any embedded input changes.
    let catalog_path = metadata_dir.join("error-catalog.yaml");
    let constraints_dir = metadata_dir.join("constraints");
    println!("cargo:rerun-if-changed={}", catalog_path.display());
    println!("cargo:rerun-if-changed={}", constraints_dir.display());
    println!("cargo:rerun-if-changed=build.rs");

    let catalog = std::fs::read_to_string(&catalog_path).unwrap_or_else(|e| {
        panic!(
            "ls-core build.rs: failed to read {}: {e}",
            catalog_path.display()
        )
    });

    let mut constraint_files: Vec<(String, String)> = Vec::new();
    if constraints_dir.is_dir() {
        let mut entries: Vec<PathBuf> = std::fs::read_dir(&constraints_dir)
            .unwrap_or_else(|e| {
                panic!(
                    "ls-core build.rs: failed to read {}: {e}",
                    constraints_dir.display()
                )
            })
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.extension().map(|x| x == "yaml").unwrap_or(false))
            .collect();
        entries.sort();
        for path in entries {
            println!("cargo:rerun-if-changed={}", path.display());
            let tr = path
                .file_stem()
                .and_then(|s| s.to_str())
                .expect("constraint file stem")
                .to_string();
            let body = std::fs::read_to_string(&path).unwrap_or_else(|e| {
                panic!(
                    "ls-core build.rs: failed to read {}: {e}",
                    path.display()
                )
            });
            constraint_files.push((tr, body));
        }
    }

    let mut generated = String::new();
    generated.push_str("// @generated by ls-core/build.rs — do not edit.\n");
    writeln!(
        generated,
        "pub(crate) const ERROR_CATALOG_YAML: &str = {catalog:?};"
    )
    .unwrap();
    generated.push_str("pub(crate) const CONSTRAINT_FILES: &[(&str, &str)] = &[\n");
    for (tr, body) in &constraint_files {
        writeln!(generated, "    ({tr:?}, {body:?}),").unwrap();
    }
    generated.push_str("];\n");

    std::fs::write(&dest, generated).expect("write embedded_metadata.rs");
}
